# Generated by Django 3.2.19 on 2023-05-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_loci', '0001_initial'),
        ('workplaces_map', '0002_auto_20230512_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField()),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='django_loci.floorplan')),
            ],
        ),
    ]
