# Generated by Django 3.2.19 on 2023-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces_map', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='follow_up_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_contacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='Unnamed Room', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('OF', 'Office'), ('LA', 'Lab'), ('LO', 'Lounge'), ('PO', 'Posterboard')], default='OF', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='workers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
