# Generated by Django 3.2.19 on 2023-05-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces_map', '0004_auto_20230515_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='geometry',
        ),
    ]
