# Generated by Django 3.2.18 on 2023-08-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces_map', '0007_textinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textinput',
            old_name='rooms_visited',
            new_name='notes',
        ),
    ]
