# Generated by Django 3.2.18 on 2023-11-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_loci', '0001_initial'),
        ('workplaces_map', '0009_textinput_is_mapped'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_priority', models.IntegerField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='django_loci.location')),
            ],
        ),
    ]
