# Generated by Django 3.2.18 on 2023-11-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces_map', '0010_extendedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedlocation',
            name='building_priority',
            field=models.IntegerField(default=0),
        ),
    ]
