# Generated by Django 3.2.18 on 2023-11-07 05:49

from django.db import migrations, models


def create_extended_locations(apps, schema_editor):
    Location = apps.get_model('django_loci', 'Location')
    ExtendedLocation = apps.get_model('workplaces_map', 'ExtendedLocation')

    # For each Location, create a corresponding ExtendedLocation if it doesn't exist
    for location in Location.objects.all():
        ExtendedLocation.objects.get_or_create(
            location=location,
            defaults={'building_priority': 0}  # Sets the default priority for new instances
        )

class Migration(migrations.Migration):

    dependencies = [
        ('workplaces_map', '0012_set_building_priority_nulls_to_0'),
    ]

    operations = [
        migrations.RunPython(create_extended_locations),
    ]
